from ubuntu:latest

RUN apt-get update && apt-get install python3-pip -y
RUN pip3 install PyYAML python-whois --break-system-packages

RUN mkdir /out
COPY whois-scanner/code /code
COPY config.yaml /config.yaml

RUN useradd -ms /bin/bash samma
RUN chown samma:samma /out
RUN chown samma:samma /code/*.py
RUN chmod 664 /code/*.py

USER samma

RUN chmod +x /code/scan.py

CMD python3 /code/scan.py
