services:
  whois-scanner:
    build:
      context: ..
      dockerfile: whois-scanner/Dockerfile
    image: ghcr.io/samma-io/detect-whois-scanner:latest
    volumes:
      - ./out:/out
    environment:
      - TARGET=example.com
      - SAMMA_IO_SCANNER=whois-scanner
      - SAMMA_IO_ID=1234
      - SAMMA_IO_TAGS=['scanner']
      - SAMMA_IO_JSON={}
      - WRITE_TO_FILE=true
      - PARSER=whois-scanner
  #filebeat:
  #  image: docker.elastic.co/beats/filebeat:7.15.0
  #  volumes:
  #    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #    - ./out:/out
